// examples/basic@vue/src/layout/core-layout.vue
<template>
  <vue-layout>
    <core-header />
    <div class="page" :style="{ animation: 'pageMask 2.4s' }">
      <slot></slot>
    </div>
    <div class="page-loading" />
  </vue-layout>
</template>

<script>
import Layout from '../components/layout.vue'
import Header from './core-header.vue'
export default {
  components: {
    'vue-layout': Layout,
    'core-header': Header
  }
}
</script>

<style lang="scss">
@import '../styles/page.scss';
@import '../styles/page-loading.scss';
</style>

// examples/nextjs-express@ssr/layouts/core-layout.tsx
import * as React from 'react'
import { Layout } from '../components'
import Header from './header'
import '../styles/page.scss'

interface CoreLayoutProps {
  children?: React.ReactNode
  context: string
}

export default class CoreLayout extends React.PureComponent<CoreLayoutProps, any> {

  static defaultProps: CoreLayoutProps = {
    children: null,
    context: '/'
  }

  render () {
    let { children, context } = this.props
    return (
      <Layout>
        <Header context={context} />
        <div className="page" style={{ animation: 'pageMask 2.4s' }}>
          {children}
        </div>
      </Layout>
    )
  }

}
