// examples/basic@vue/src/layout/core-layout.vue
<template>
  <vue-layout>
    <core-header />
    <div class="page" :style="{ animation: 'pageMask 2.4s' }">
      <slot></slot>
    </div>
    <div class="page-loading" />
  </vue-layout>
</template>

<script>
import Layout from '../components/layout.vue'
import Header from './core-header.vue'
export default {
  components: {
    'vue-layout': Layout,
    'core-header': Header
  }
}
</script>

<style lang="scss">
@import '../styles/page.scss';
@import '../styles/page-loading.scss';
</style>

// examples/basic@react/src/pages/core-layout.jsx
import React, { PureComponent } from 'react'
import PropTypes from 'prop-types'
import { Layout } from '../components'
import Header from './header'
import '../styles/page.scss'
import '../styles/page-loading.scss'

export default class CoreLayout extends PureComponent {

  static propTypes = {
    children: PropTypes.node,
  }

  static defaultProps = {
    children: null,
  }

  render () {
    let { children } = this.props
    return (
      <Layout>
        <Header />
        <div className="page" style={{ animation: 'pageMask 2.4s' }}>
          {children}
        </div>
        <div className="page-loading" />
      </Layout>
    )
  }
}
