// examples/nextjs-express@ssr/layouts/header.tsx
import * as React from 'react'
import Link from 'next/link'
import logo from '../static/images/logo.png'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import { nextPageClick } from '../redux/action'

interface HeaderProps {
  context: string
  actions?: {
    nextPageClick: Function
  }
}

@connect(
  state => ({
    ...state
  }),
  dispatch => ({
    actions: bindActionCreators({ nextPageClick }, dispatch)
  })
)
export default class Header extends React.PureComponent<HeaderProps, any> {

  static defaultProps: HeaderProps = {
    context: '/'
  }

  render () {
    let { context } = this.props
    return (
      <div className="layout-header">
        <div className="logo">
          <img src={logo} />
        </div>
        <div className="nav">
          <ul>
            <li className={activeClassName('/', context)}><Link href='/'><a onClick={() => this.props.actions.nextPageClick('home')}>Home</a></Link></li>
            <li className={activeClassName('/about', context)}><Link href='/about'><a onClick={() => this.props.actions.nextPageClick('about')}>About</a></Link></li>
          </ul>
        </div>
        <style jsx>{`
        // ------------------------------------
        // Sass Style
        // ------------------------------------
        .layout-header {
          display: flex;
          flex-direction: column;
          //justify-content: center;
          align-items: center;
          padding: 150px 20px 80px;
        
          .logo {
            max-width: 400px;
            img {
              max-width: inherit;
            }
          }
        
          .nav {
            margin-top: 50px;
        
            ul {
              list-style-type: none;
              padding: 0;
              display: flex;
        
              li {
                margin: 0 15px;
                font-size: 14px;
        
                a {
                  font-size: 1.5em;
                  color: #343434;
                  font-weight: bold;
                  position: relative;
        
                  &::after {
                    content: "";
                    position: absolute;
                    bottom: 0;
                    left: 50%;
                    width: 0;
                    height: 3px;
                    background: #ff8011;
                    opacity: .2;
                    transition: all .5s;
                    bottom: -5px;
                  }
        
                  &:hover {
                    &::after{
                      left:0%;
                      width:100%;
                      opacity:.7
                    }
                  }
                }
        
                &.active a {
                  color: #ff6633;
                }
              }
            }
          }
        }
        `}</style>
      </div>
    )
  }
}

const activeClassName = (linkname: string, context: string): string => linkname === context ? 'active' : ''

// examples/basic@vue/src/header.vue
<template>
  <div class="layout-header">
    <div class="logo">
      <img :src="logo" />
    </div>
    <div class="nav">
      <ul>
        <li :class="activeClassName('/')"><router-link to="/" >Home</router-link></li>
        <li :class="activeClassName('/about')"><router-link to="/about">About</router-link></li>
      </ul>
    </div>
  </div>
</template>

<script>
import * as Images from './assets/images'
import * as utils from './utils'


export default {
  data () {
    return {
      logo: utils.assetUrl(Images.logo)
    }
  },
  mounted () {
    
  },
  methods: {
    activeClassName (linkname) {
      return utils.isActiveLink(linkname, this.$router.history.current.path) ? 'active' : ''
    }
  }
}
</script>

<style lang="scss">
.layout-header {
  display: flex;
  flex-direction: column;
  //justify-content: center;
  align-items: center;
  padding: 150px 20px 80px;

  .logo {
    max-width: 400px;
    img {
      max-width: inherit;
    }
  }

  .nav {
    margin-top: 50px;

    ul {
      list-style-type: none;
      padding: 0;
      display: flex;

      li {
        margin: 0 15px;
        font-size: 14px;

        a {
          font-size: 1.5em;
          color: #343434;
          font-weight: bold;
          position: relative;

          &::after {
            content: "";
            position: absolute;
            bottom: 0;
            left: 50%;
            width: 0;
            height: 3px;
            background: #ff8011;
            opacity: .2;
            transition: all .5s;
            bottom: -5px;
          }

          &:hover {
            &::after{
              left:0%;
              width:100%;
              opacity:.7
            }
          }
        }

        &.active a {
          color: #ff6633;
        }
      }
    }
  }
}
</style>
